{% set name = "clmm" %}
{% set version = "1.14.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/clmm-{{ version }}.tar.gz
  sha256: edfab4226e7eba3a21b5cf938d5ac1a72cedfa020c6c6d9796e1021a99b13afc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13a0
    - astropy-base >=4,!=5.0
    - matplotlib-base
    - numpy >=1.17
    - scipy >=1.3
    - healpy
    - qp-prob

test:
  imports:
    - clmm
  requires:
    - pip
    - pyccl
    - python {{ python_min }}

about:
  home: https://lsstdesc.org/CLMM/
  summary: A comprehensive package for galaxy cluster weak lensing
  dev_url: https://github.com/LSSTDESC/CLMM
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eduardojsbarroso
    - beckermr
